# Generated by Django 6.0.3 on 2026-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khoa_phong', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_khoa_phong', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'khoa_phong',
            },
        ),
    ]
