# Generated by Django 6.0.3 on 2026-05-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0002_khoaphong'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thiet_bi', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_thiet_bi', models.CharField(max_length=255)),
                ('ngay_su_dung', models.DateField(blank=True, null=True)),
                ('loai_thiet_bi', models.CharField(choices=[('Máy Tính', 'Máy Tính'), ('Máy In', 'Máy In'), ('Máy Scan', 'Máy Scan'), ('Máy Photo', 'Máy Photo'), ('Thiết Bị Mạng', 'Thiết Bị Mạng'), ('Quét Mã Vạch', 'Quét Mã Vạch'), ('Khác', 'Khác')], max_length=50)),
                ('khoa_phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hethong.khoaphong')),
            ],
            options={
                'db_table': 'thiet_bi',
            },
        ),
    ]
