# Generated by Django 6.0.3 on 2026-05-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0003_thietbi'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuSuaChua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_sua_chua', models.DateField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.thietbi')),
            ],
            options={
                'db_table': 'lich_su_sua_chua',
            },
        ),
    ]
