# Generated by Django 6.0.3 on 2026-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0004_lichsusuachua'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='dang_sua_chua',
            field=models.BooleanField(default=False),
        ),
    ]
