# Generated by Django 6.0.3 on 2026-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0005_thietbi_dang_sua_chua'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsusuachua',
            name='ghi_chu_hoan_tat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsusuachua',
            name='ngay_hoan_tat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
