# Generated by Django 6.0.3 on 2026-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0006_lichsusuachua_ghi_chu_hoan_tat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_vat_tu', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_vat_tu', models.CharField(max_length=255)),
                ('so_luong', models.IntegerField(default=0)),
                ('han_su_dung', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vat_tu',
            },
        ),
    ]
