# Generated by Django 6.0.3 on 2026-05-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0007_vattu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_phieu', models.DateField()),
            ],
            options={
                'db_table': 'phieu_nhap_kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.vattu')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.phieunhapkho')),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap',
            },
        ),
    ]
