# Generated by Django 6.0.3 on 2026-05-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0008_phieunhapkho_chitietphieunhap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('ngay_phieu', models.DateField()),
            ],
            options={
                'db_table': 'phieu_xuat_kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.vattu')),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.phieuxuatkho')),
            ],
            options={
                'db_table': 'chi_tiet_phieu_xuat',
            },
        ),
    ]
