# Generated by Django 6.0.3 on 2026-05-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0009_phieuxuatkho_chitietphieuxuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='is_hong_han',
            field=models.BooleanField(default=False),
        ),
    ]
