# Generated by Django 6.0.3 on 2026-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0010_thietbi_is_hong_han'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='hinh_anh_thanh_ly',
            field=models.ImageField(blank=True, null=True, upload_to='thanhly/'),
        ),
    ]
