# Generated by Django 6.0.3 on 2026-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0011_thietbi_hinh_anh_thanh_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='is_thanh_ly',
            field=models.BooleanField(default=False),
        ),
    ]
