# Generated by Django 6.0.3 on 2026-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0012_thietbi_is_thanh_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='thietbi',
            name='ly_do_thanh_ly',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thietbi',
            name='ngay_thanh_ly',
            field=models.DateField(blank=True, null=True),
        ),
    ]
