# Generated by Django 6.0.3 on 2026-05-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0013_thietbi_ly_do_thanh_ly_thietbi_ngay_thanh_ly'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhThanhLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='thanhly/')),
                ('thiet_bi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_anh_thanh_ly', to='hethong.thietbi')),
            ],
        ),
    ]
