# Generated by Django 6.0.3 on 2026-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0014_hinhanhthanhly'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_nhan_vien', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nhan_vien',
            },
        ),
    ]
