# Generated by Django 6.0.3 on 2026-05-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0015_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoBanCNTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_giao_ban', models.DateField()),
                ('tinh_trang_tiep_nhan', models.TextField()),
                ('cach_xu_ly', models.TextField()),
                ('trang_thai', models.CharField(choices=[('Đã hoàn thành', 'Đã hoàn thành'), ('Đang xử lý', 'Đang xử lý'), ('Chưa xử lý', 'Chưa xử lý'), ('Cần theo dõi thêm', 'Cần theo dõi thêm'), ('Khác', 'Khác')], max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('khoa_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.khoaphong')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.nhanvien')),
            ],
            options={
                'db_table': 'giao_ban_cntt',
            },
        ),
    ]
