# Generated by Django 6.0.3 on 2026-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0016_giaobancntt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattu',
            name='noi_de_vat_tu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
