# Generated by Django 6.0.3 on 2026-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0017_vattu_noi_de_vat_tu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattu',
            name='is_tieu_hao',
            field=models.BooleanField(default=False),
        ),
    ]
