# Generated by Django 6.0.3 on 2026-05-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0018_vattu_is_tieu_hao'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhapkho',
            name='khoa_phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hethong.khoaphong'),
        ),
    ]
