# Generated by Django 6.0.3 on 2026-05-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0019_phieunhapkho_khoa_phong'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonKhoKhoaPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('khoa_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.khoaphong')),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.vattu')),
            ],
            options={
                'db_table': 'ton_kho_khoa_phong',
                'unique_together': {('khoa_phong', 'vat_tu')},
            },
        ),
    ]
