# Generated by Django 6.0.3 on 2026-05-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0020_tonkhokhoaphong'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuxuatkho',
            name='khoa_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_nhan_kho', to='hethong.khoaphong'),
        ),
        migrations.AddField(
            model_name='phieuxuatkho',
            name='khoa_phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_xuat_kho', to='hethong.khoaphong'),
        ),
    ]
