# Generated by Django 6.0.3 on 2026-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0021_phieuxuatkho_khoa_nhan_phieuxuatkho_khoa_phong'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonkhokhoaphong',
            name='so_luong_hong',
            field=models.IntegerField(default=0),
        ),
    ]
