# Generated by Django 6.0.3 on 2026-05-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0022_tonkhokhoaphong_so_luong_hong'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuBaoHong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('ngay_bao_hong', models.DateTimeField(auto_now_add=True)),
                ('khoa_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khoa_nhan_hong', to='hethong.khoaphong')),
                ('khoa_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khoa_xuat_hong', to='hethong.khoaphong')),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hethong.vattu')),
            ],
            options={
                'db_table': 'lich_su_bao_hong',
            },
        ),
    ]
