# Generated by Django 6.0.3 on 2026-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0024_lichsutieuhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsutieuhao',
            name='is_hong',
            field=models.BooleanField(default=False),
        ),
    ]
