# Generated by Django 6.0.3 on 2026-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0025_lichsutieuhao_is_hong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaobancntt',
            name='nhan_vien',
        ),
        migrations.AddField(
            model_name='giaobancntt',
            name='nhan_vien',
            field=models.ManyToManyField(to='hethong.nhanvien'),
        ),
    ]
