# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0026_remove_giaobancntt_nhan_vien_giaobancntt_nhan_vien'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattu',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
